name: OpenShift

on: 
  push: 
    branches: [ master ] 
    
env:

  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.GIT_TOKEN }}
  IMAGE_REGISTRY: ghcr.io/simplai-monex/naira

  # Nairatest
  #APP_NAME: naira-monex-db
  # Dev
  #APP_NAME: naira-monex-db-dev
  # Prod
  APP_NAME: naira-monex-db-pre

  IMAGE_TAGS: latest

  
jobs: 
  Deploy-environment-pre: 
    name: DeployConnectorsOpenshift 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout the repository 
      uses: actions/checkout@v3 

    - name: Log in to ghcr.io 
      uses: redhat-actions/podman-login@v1 
      with: 
        username: ${{ env.REGISTRY_USER }} 
        password: ${{ env.REGISTRY_PASSWORD }} 
        registry: ${{ env.IMAGE_REGISTRY }}
        
    - name: Log in to redhat registry
      uses: redhat-actions/podman-login@v1 
      with: 
        username: dalcalde@simplai.es
        password: HakunaMatata1
        registry: registry.redhat.io
        
        
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}

        dockerfiles: |
          ./Dockerfile
          
    - name: Push To Github Package 
      id: push-to-quay 
      uses: redhat-actions/push-to-registry@v2 
      with: 
        image: ${{ steps.build-image.outputs.image }} 
        tags: ${{ steps.build-image.outputs.tags }} 
        registry: ${{ env.IMAGE_REGISTRY }} 

